### ISSUE TITLE
Not working on Chrome for Mac

### ISSUE THREAD

**Issue by Djemel** [andrei-markeev/cisar#17] opened 2016-04-07 19:41 UTC
It can successfully use CISAR on Chrome for Windows. But unfortunately, I lately switch to a MacBook Pro and I can not get CISAR to work on Chrome for Mac.
When I open the extension from any SharePoint site in the devtool - the panel on the left side keep showing an animated loading icon indefinitely.
Any help ?

**Comment by TotallyInformation** [comment] 2016-05-12 11:48
Happening to me as well but I'm on Windows 10 with the latest live version of Chrome. Using SharePoint Online.

**Comment by andrei-markeev** [comment] 2016-05-12 12:17
Hi guys, just checked and everything seems to be working fine for me. I'm using Chrome on Windows 10, Windows 7 and also on Linux. It is more likely to be related not to the OS, but to the particular page or site where it doesn't work.

I would greatly appreciate if you could try Cisar on some other sites and pages and see if it works there. And if it does, then give me some more details about sites/pages where it doesn't work. For example, is it a publishing site? Is it a subsite? Are there some unusual symbols in the URL? Do you use the preview of new libraries design maybe? Is it list or library page or a webpart page where you try Cisar? Etc.

Also it would be a good idea to check that you're using the latest version of Cisar from webstore, which is currently 1.3. You can check it by navigating to chrome://extensions

Thanks!

**Comment by Djemel** [comment] 2016-05-12 12:50
It works nearly 100% of the time in Windows 7. But never on OSX what ever SharePoint site I try.

**Comment by Djemel** [comment] 2016-05-13 19:04
Tried 1.3 available in the Chrome "store" - and even try the one "2.0" directly from GitHub using dev mode.
Same results with both - does not work with Chrome on OSX.

**Comment by devManderson** [comment] 2016-08-17 06:48
Panel on the left side keep showing an animated loading icon indefinitely. +1 On Windows 10

Tried cisar from the chrome webstore and directly from github. Tried it on several SharePoint online List and Sites (publishing). Old & New List/Libary design....

**Comment by andrei-markeev** [comment] 2016-08-19 08:56
New list/library experience will not work. It's not compatible with CSR and as far as I know, at this point there's no way to customize new experience lists/libraries at all.

@devManderson I'm trying on Win 10 and everything seems to be working fine on normal lists and libraries with Cisar 2.0.1 from webstore. I don't have Mac so cannot investigate what is going on there.

Usually infinite loading means that there was some critical error during initialization.

How I usually investigate it is I go to Cisar in the DevTools and then press Ctrl+Shift+I. This opens **second** DevTools (where you can debug the first DevTools), and there in the Console most likely you'll see the error message.

Since I cannot reproduce this on my computers, it would be very helpful if you guys can do what I explained above and post the error message here...

**Comment by devManderson** [comment] 2016-08-19 11:27
@andrei-markeev  thx for reply.  I get this on a normal list (classic mode)

![image](https://cloud.githubusercontent.com/assets/21075250/17808451/92b2ed3c-6610-11e6-9dff-7af288d55441.png)

**Comment by devManderson** [comment] 2016-08-19 11:36
Ok, I guess I fixed it (well at least for myself):

https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

Now it seems to work :)

**Comment by andrei-markeev** [comment] 2016-08-19 11:47
Yep exactly, I just found same article. If I remember correctly, Cisar uses localStorage to "cache" files contents so that it doesn't need to fetch them every time. I will review the code - maybe I can detect local storage unavaliability and fall back to simple variables, or at least I can change the code to provide a sensible error message to other people who may face it.

Thanks for reporting this and please don't hesitate to report anything else you notice, this is really appreciated! :)

**Comment by andrei-markeev** [comment] 2017-05-04 10:43
I just checked from a MacBook Pro in Chrome and it works fine. There were a lot of changes since the bug was created so it is quite likely that some of those changes fixed the issue. Closing this (but feel free to still comment or create another issue if you still have issues on your Mac!).

**Closed as completed by andrei-markeev** 2017-05-04 10:43 UTC
